# Generated by Django 4.2.4 on 2023-08-08 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_review_parent_alter_post_id_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb0f90dd-dbee-4630-abf1-bcf0c055c8f5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25ef98cf-2737-4167-a882-755f43b8e588'), editable=False, primary_key=True, serialize=False),
        ),
    ]
