# Generated by Django 4.2.4 on 2023-08-11 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_id_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ddd6a92e-df76-4198-b23b-00974e4723cb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
