# Generated by Django 4.2.4 on 2023-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postlike_postlike_onelikeperpostperuser'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postlike',
            name='OneLikePerPostPerUser',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='liked_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='OneLikePerPostPerUser'),
        ),
    ]
