# Generated by Django 4.2.4 on 2023-08-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_postlike_onelikeperpostperuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='vote_total',
            field=models.IntegerField(default=0),
        ),
    ]
