# Generated by Django 4.2.4 on 2023-08-13 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
