# Generated by Django 4.2.4 on 2023-08-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_from_location_customuser_lives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ORDINARY', 'Ordinary'), ('ADMIN', 'Admin'), ('ADMINISTRATOR', 'Administrator'), ('SUPERUSER', 'Superuser')], default='ORDINARY', max_length=16),
        ),
    ]
