# Generated by Django 4.2.4 on 2023-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
