# Generated by Django 4.2.4 on 2023-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(default='accounts/images/default-cover.svg', upload_to='accounts/images/'),
        ),
    ]
