# Generated by Django 4.2.4 on 2023-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_friendlist_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
